# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Provider Shared Configuration
  config.ssh.insert_key = false

  # Hyper-V Provider Specific Configuration
  config.vm.provider "hyperv" do |h|
    h.vmname = "vagrant-debian12"
    h.enable_virtualization_extensions = true
    h.linked_clone = true
    h.cpus = 2
    h.memory = 2048
    h.maxmemory = 2048
  end

  # VMware Workstation Provider Specific Configuration
  config.vm.provider "vmware_desktop" do |w|
    w.vmx['displayname'] = "vagrant-debian12"
    w.vmx['memsize'] = "2048"
    w.vmx['numvcpus'] = "2"
  end

  # Virtualbox Provider Specific Configuration
  config.vm.provider "virtualbox" do |v|
    v.name = "vagrant-debian12"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "debian12" do |debian12|
    # VM Shared Configuration
    debian12.vm.box = "maroskukan/debian12"
    debian12.vm.hostname = "debian12"

    # Hyper-V VM Specific Configuration
    debian12.vm.provider 'hyperv' do |h, override|
      override.vm.box = "file://builds/debian12-hyperv.box"
      override.vm.network "public_network", bridge: "Default Switch"
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end

    # VMware Workstation VM Specific Configuration
    debian12.vm.provider 'vmware_desktop' do |w, override|
      override.vm.box = "file://builds/debian12-vmware.box"
      override.vm.synced_folder ".", "/vagrant", disabled: true
    end

    # Virtualbox VM Specific Configuration
    debian12.vm.provider 'virtualbox' do |v, override|
      override.vm.box = "file://builds/debian12-virtualbox.box"
      override.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end

  # VM Shared Provisioning
  config.vm.provision "shell", inline: "cat /etc/os-release"
end