# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Provider Shared Configuration
  config.ssh.insert_key = false

  # Hyper-V Provider Specific Configuration
  config.vm.provider "hyperv" do |h|
    h.vmname = "vagrant-ubuntu2204"
    h.linked_clone = true
    h.memory = 2048
    h.maxmemory = 2048
  end

  # VMware Workstation Provider Specific Configuration
  config.vm.provider "vmware_desktop" do |w|
    w.vmx['displayname'] = "vagrant-ubuntu2304"
    w.vmx['memsize'] = "2048"
    w.vmx['numvcpus'] = "2"
  end  

  # Virtualbox Provider Specific Configuration
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "ubuntu2204" do |ubuntu2204|
    # VM Shared Configuration
    ubuntu2204.vm.box = "maroskukan/ubuntu2204"
    ubuntu2204.vm.hostname = "ubuntu2204"

    # Hyper-V VM Specific Configuration
    ubuntu2204.vm.provider 'hyperv' do |h, override|
      override.vm.box = "file://builds/ubuntu2204-hyperv.box"
      override.vm.network "public_network", bridge: "Default Switch"
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end

    # VMware Workstation VM Specific Configuration
    ubuntu2204.vm.provider 'vmware_desktop' do |w, override|
      override.vm.box = "file://builds/ubuntu2204-vmware.box"
      override.vm.synced_folder ".", "/vagrant", disabled: true
    end

    # Virtualbox VM Specific Configuration
    ubuntu2204.vm.provider 'virtualbox' do |v, override|
      override.vm.box = "file://builds/ubuntu2204-virtualbox.box"
      override.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end

  # VM Shared Provisioning
  config.vm.provision "shell", inline: "cat /etc/os-release"
end